DROP TABLE IF EXISTS "user" CASCADE;

create table "user" (
    id integer generated by default as identity (start with 1),
    name varchar(50) not null,
    username varchar(50) not null,
    email varchar(100) not null,
    primary key (id)
);